"""add_aprobada_fields_to_actas

Revision ID: 793255fca25a
Revises: c9d4edbd238a
Create Date: 2026-03-18 17:45:16.880078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793255fca25a'
down_revision: Union[str, None] = 'c9d4edbd238a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actas', sa.Column('aprobada_por', sa.UUID(), nullable=True))
    op.add_column('actas', sa.Column('aprobada_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'actas', 'usuarios', ['aprobada_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actas', type_='foreignkey')
    op.drop_column('actas', 'aprobada_at')
    op.drop_column('actas', 'aprobada_por')
    # ### end Alembic commands ###
