"""Add UsoApi model for accurate cost tracking

Revision ID: 7f4c8a42dccb
Revises: 793255fca25a
Create Date: 2026-03-26 18:02:25.305413
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4c8a42dccb'
down_revision: Union[str, None] = '793255fca25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uso_api',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiencia_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('servicio', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('costo_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audiencia_id'], ['audiencias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_api_audiencia_id'), 'uso_api', ['audiencia_id'], unique=False)
    op.create_index(op.f('ix_uso_api_servicio'), 'uso_api', ['servicio'], unique=False)
    op.create_index(op.f('ix_uso_api_usuario_id'), 'uso_api', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uso_api_usuario_id'), table_name='uso_api')
    op.drop_index(op.f('ix_uso_api_servicio'), table_name='uso_api')
    op.drop_index(op.f('ix_uso_api_audiencia_id'), table_name='uso_api')
    op.drop_table('uso_api')
    # ### end Alembic commands ###
